### ISSUE TITLE
Should we turn white to transparent?

### ISSUE THREAD

**Issue by dankohn** [cncf/svg-autocrop#3]
For example, in Anchore

https://github.com/cncf/svg-autocrop/blob/master/fixtures/anchore.output.svg

It might make sense only to do for non-enclosed white sections.

**Comment by ZeusTheTrueGod** [comment]
We can detect this issue, but I'm not sure if there is an easy fix

**Comment by ZeusTheTrueGod** [comment]
The white background will be fixed manually. Still, we can certainly detect that we have a white background and add a warning

**Comment by dankohn** [comment]
Let's not bother for now.
