### ISSUE TITLE
the wikipedia flag of guam does not render for the lfph landscape

### ISSUE THREAD

**Issue by dahoum** [cncf/svg-autocrop#32]
the wikipedia flag of guam

https://upload.wikimedia.org/wikipedia/commons/0/07/Flag_of_Guam.svg

returns this error (attached)

![65F69EB3-32A3-41F0-84F5-B2F815F52B0E](https://user-images.githubusercontent.com/23339925/92791304-da437580-f3ac-11ea-9a73-8abd96d77e7f.png)

can the autocrop be improved to handle that or shall we manually rebuild it and inform the maintainers of the wikipedia page that their svg is not good?

**Comment by dankohn** [comment]
Neither. There are some SVGs we just can't handle automatically.
