### ISSUE TITLE
Detect bad SVGs

### ISSUE THREAD

**Issue by dankohn** [cncf/svg-autocrop#4]
This doesn't load in Chrome. Can we detect that and trigger an error?
[singularity.svg.zip](https://github.com/cncf/svg-autocrop/files/2741545/singularity.svg.zip)

**Comment by ZeusTheTrueGod** [comment]
It is saved as `badSvgMarkup.input.svg`

**Comment by ZeusTheTrueGod** [comment]
And the error message is in the badSvgMarkup.error.txt
