### ISSUE TITLE
Image conversion fails on clean SVG

### ISSUE THREAD

**Issue by jmertic** [cncf/svg-autocrop#45]
![vates](https://user-images.githubusercontent.com/296737/205446691-3318eb21-a47f-4b74-8f37-4d10178e5142.svg)

Error received:

svg autocrop failed: Cannot read properties of undefined (reading 'each')

**Comment by AndreyKozlov1984** [comment]
I was able to track it down to a wrong `<style>` definition

**Comment by AndreyKozlov1984** [comment]
@jmertic 
line 3, left from the word `isolation` you can see a "`" symbol, which breaks everything!

<img width="1401" alt="image" src="https://user-images.githubusercontent.com/230982/205885642-64858508-556d-4427-99e0-40583aa30f93.png">

**Comment by AndreyKozlov1984** [comment]
a`{isolation: isolate;} is a wrong css selector, and it breaks everything

**Comment by AndreyKozlov1984** [comment]
Just remove the "`" and all starts to work

**Comment by jmertic** [comment]
Great catch! I tried running through the validators, but I bet it never really checks inline styles. Thanks @AndreyKozlov1984 !
