### ISSUE TITLE
Use this as a fixture

### ISSUE THREAD

**Issue by dankohn** [cncf/svg-autocrop#5]
Auto-cropping originally failed on https://raw.githubusercontent.com/MitocGroup/deep-framework/master/docs/logo.svg. Does it work now? Any idea why it had trouble before?

**Comment by ZeusTheTrueGod** [comment]
It works now.
![image](https://user-images.githubusercontent.com/230982/50919301-5b10d800-143a-11e9-8db3-03acee0295e3.png)

**Comment by ZeusTheTrueGod** [comment]
closed via 7f9f168
